<?php

$routeur = [
	"#^/critique/$#" => "ControlerFront@home",
	"#^/critique/film/accueil$#" => "ControlerFront@home",
	"#^/critique/film/dernier-film#" => "ControlerFront@lastExit",
	"#^/critique/film/formulaire-admin$#" => "ControlerFront@formAdmin",
	"#^/critique/film/connexion-admin$#" => "ControlerFront@connectAdmin",
	"#^/critique/film/formulaire-connexion#" => "ControlerFront@formConnect",
	"#^/critique/film/deconnect$#" => "ControlerFront@deconnect",
	"#^/critique/film/inscription$#" => "ControlerFront@inscription",
	"#^/critique/film/connexion$#" => "ControlerFront@connect",
	"#^/critique/film/administration$#" => "ControlerBack@admin",
	"#^/critique/film/ajout-film$#" => "ControlerBack@addPost",
	"#^/critique/film/ajout-fiche-film$#" => "ControlerBack@savePost",
	"#^/critique/film/([0-9]+)/suprimer$#" => "ControlerBack@deletePost",
	"#^/critique/film/([0-9]+)$#" => "ControlerFront@getPost",
	"#^/critique/film/([0-9]+)/report$#" => "ControlerFront@getPost",
	"#^/critique/film/([0-9]+)/ajout-commentaire$#" => "ControlerFront@addComment",
	"#^/critique/film/([0-9]+)/modification$#" => "ControlerBack@formUpdatePost",
	"#^/critique/film/([0-9]+)/modification-fiche-film$#" => "ControlerBack@updatePost",
	"#^/critique/film/category/([a-zA-Z0-9\-]+)#" => "ControlerFront@postCategory",
	"#^/critique/film/recherche-film$#" => "ControlerFront@search",
	"#^/critique/film/contact$#" => "ControlerFront@formContact",
	"#^/critique/film/message-contact$#" => "ControlerFront@contact",
	"#^/critique/film/utilisateur$#" => "ControlerFront@userPage",
	"#^/critique/film/admin-contact$#" => "ControlerBack@getContact",
	"#^/critique/film/contact/([a-zA-Z0-9]+)$#" => "ControlerBack@getOneContact",
	"#^/critique/film/contact/delete/([0-9]+)$#" => "ControlerBack@deleteContact",
	"#^/critique/film/modification/commentaire-([0-9]+)$#" => "ControlerFront@formUpdateComment",
	"#^/critique/film/modification/commentaire/([0-9]+)/([0-9]+)$#" => "ControlerFront@updateComment",
	"#^/critique/film/report/commentaire/([0-9]+)/([0-9]+)$#" => "ControlerFront@addReport",
	"#^/critique/film/commentaire-signale#" => "ControlerBack@listReport",
	"#^/critique/film/suprimer/signalement/([0-9]+)$#" => "ControlerBack@deleteReport",
	"#^/critique/film/suprimer/commentaire/([0-9]+)$#" => "ControlerBack@deleteComment",
	"#^/critique/film/carte-cinema-paris$#" => "ControlerFront@carte"

];